### ISSUE TITLE
github-exporter Deployment needs different Strategy when using persistence.enabled=true

### ISSUE THREAD

**Issue by ecobee-adriand** [promhippie/charts#179]
The github-exporter Deployment gets stuck on an update, when using a PVC with the default settings.

Full spec generated using:
`helm template github-exporter -n default --set persistence.enabled=true  promhippie/github-exporter`

Snippets below for reference (labels and annotations removed for brevity).

```
---
# Source: github-exporter/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: github-exporter
  namespace: default
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1G"
---
# Source: github-exporter/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-exporter
spec:
  replicas: 1
```

When using these settings, the `.spec.strategy` uses the k8s defaults:
```
spec:
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
```

As a result, the existing pod that's using the PVC stays up until a new pod is ready, however the new pod cannot come up as it cannot attach the PVC.

I believe the easiest way to resolve this is the `strategy` to be exposed via configuration, either allowing a change to the type, and/or changes for the maxSurge/maxUnavailable.
